.TH YED-FORMATTER 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
formatter \- automatically formats C and C++ files.
.SH CONFIGURATION
.SS formatter-auto [ yes / no ]
.SH COMMANDS
.SS run-formatter
Formats C and C++ files.
.SH BUFFERS
None
.SH NOTES
.P
This plugin is much like the gg=G command in vim.
.SH VERSION
0.0.1
.SH KEYWORDS
automatic, format, c, cpp, c++, formatting, files
